### ISSUE TITLE
Can't compile on RPI 2 v1.1

### ISSUE THREAD

**Issue by fazibear** [raylib-rs/raylib-rs#74]
Trying to compile simple app with raylib-rs directly on RPI 2,
and got lot of errors like this:

```rust
error[E0308]: mismatched types
   --> /home/fazibear/.cargo/registry/src/index.crates.io-1cd66030c949c28d/raylib-5.0.1/src/core/callbacks.rs:100:37
    |
100 |     let a = unsafe { CStr::from_ptr(a) };
    |                      -------------- ^ expected `*const u8`, found `*const i8`
    |                      |
    |                      arguments to this function are incorrect
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`
note: associated function defined here
   --> /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ffi/c_str.rs:284:25

```

Any idea why?
Thanks for help!

```
$ uname -a
Linux rpi 6.6.20-v7+ #1738 SMP Tue Mar  5 14:43:23 GMT 2024 armv7l GNU/Linux
```
```
$ rustc --version
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
```

**Comment by fazibear** [comment]
Found what is happening ... https://github.com/deltaphc/raylib-rs/issues/191

**Comment by theoparis** [comment]
I'm having the same issue with Asahi Linux on a M2 MBP 😕

**Comment by IoIxD** [comment]
@fazibear Can you try compiling again?
